<?php
/**
 * @file
 * Provide groups on flexiform.
 */

/**
 * Implements hook_menu().
 */
function flexiform_element_group_menu() {
  $items["admin/structure/flexiforms/manage/%/form-fields/groups/%field_group_menu/delete"] = array(
    'load arguments' => array('flexiform', 4, '4', '%map'),
    'title' => 'Delete',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('field_group_delete_form', 7),
    'type' => MENU_CALLBACK,
    'file' => 'field_group.field_ui.inc',
    'file path' => drupal_get_path('module', 'field_group'),
    'access callback' => TRUE,
  );

  return $items;
}

/**
 * Implements hook_form_field_group_delete_form_alter().
 */
function flexiform_element_group_form_field_group_delete_form_alter(&$form, &$form_state) {
  if ($form['#group']->entity_type == 'flexiform') {
    $form['#redirect'] = array(
      0 => "admin/structure/flexiforms/manage/{$form['#group']->bundle}/form-fields",
    );
  }
}

/**
 * Implements hook_form_flexiform_manage_form_fields_form_alter().
 */
function flexiform_element_group_form_flexiform_manage_form_fields_form_alter(&$form, &$form_state) {
  form_load_include($form_state, 'inc', 'flexiform_element_group', 'flexiform_element_group.admin');
  flexiform_element_group_manage_form_fields_form_alter($form, $form_state);
}

/**
 * Implements hook_flexiform_build_alter().
 */
function flexiform_element_group_flexiform_build_alter(&$form, &$form_state, $flexiform) {
  if ($flexiform->builder != 'FlexiformBuilderFlexiform') {
    return;
  }

  // Dirty hack.
  $form['#entity_type'] = 'flexiform';
  $form['#bundle'] = $flexiform->form;

  field_group_attach_groups($form, 'form', $form_state);
}
